#!/usr/bin/env python3
"""Generate the deterministic human view of the canonical component catalog."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
DEFAULT_CATALOG = ROOT / "assets" / "component-catalog" / "blazex-component-catalog-v0.1.0.json"
DEFAULT_OUTPUT = ROOT / "assets" / "component-catalog" / "blazex-component-catalog-v0-1-0-generated.md"
CATEGORY_ORDER = [
    "foundation-provider",
    "layout-content",
    "actions-feedback",
    "navigation-disclosure",
    "forms-input",
    "data-visualization",
    "browser-interaction",
]


def _escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_catalog(catalog: dict[str, Any]) -> str:
    families = catalog["families"]
    exceptions = catalog["exceptions"]
    category_counts = Counter(record["category"] for record in families)
    lifecycle_counts = Counter(record["lifecycle_status"] for record in families)
    exception_counts = Counter(record["classification"] for record in exceptions)
    disposition_counts = Counter(record["classification"]["disposition"] for record in families)
    delivery_counts = Counter(record["implementation"]["delivery_state"] for record in families)

    lines = [
        "---",
        'title: "BlazeX normalized component-family inventory v0.1.0"',
        "kind: note",
        'created: "2026-09-03"',
        "maturity: stable",
        "tags:",
        "  - bh-00",
        "  - component-catalog",
        "  - generated",
        "  - mudblazor",
        "aliases:",
        '  - "BlazeX generated component catalog"',
        "---",
        "",
        "# BlazeX normalized component-family inventory v0.1.0",
        "",
        "> Generated deterministically from the canonical JSON catalog. Do not edit this file by hand.",
        "",
        "## Catalog identity",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Catalog ID | `{_escape(catalog['catalog_id'])}` |",
        f"| Catalog version | `{_escape(catalog['catalog_version'])}` |",
        f"| Schema version | `{_escape(catalog['schema_version'])}` |",
        f"| Reference | `{_escape(catalog['reference_id'])}` |",
        f"| Catalog status | `{_escape(catalog['catalog_status'])}` |",
        f"| Canonical source | `{_escape(catalog['authored_source'])}` |",
        f"| Sort order | `{_escape(catalog['sort_order'])}` |",
        f"| Family count | {len(families)} |",
        f"| Exception count | {len(exceptions)} |",
        "",
        "The catalog records source identity only at this phase. Every product disposition,",
        "delivery tier, package, capability, fallback, renderer/runtime assessment, native",
        "strategy, implementation state, and evidence link remains explicitly unassigned.",
        "",
        "## Category summary",
        "",
        "| Category | Families |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{category}` | {category_counts[category]} |" for category in CATEGORY_ORDER)
    lines.extend([
        "",
        "## Families",
        "",
        "| Stable ID | Display name | Source family | Category | Source identifiers | Lifecycle | Disposition | Tier | Delivery state |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ])
    for record in families:
        source_identifiers = ", ".join(f"`{_escape(value)}`" for value in record["source"]["source_identifiers"])
        lines.append(
            "| `{id}` | {display} | `{source}` | `{category}` | {identifiers} | `{lifecycle}` | `{disposition}` | `{tier}` | `{delivery}` |".format(
                id=_escape(record["id"]),
                display=_escape(record["display_name"]),
                source=_escape(record["source"]["source_family"]),
                category=_escape(record["category"]),
                identifiers=source_identifiers,
                lifecycle=_escape(record["lifecycle_status"]),
                disposition=_escape(record["classification"]["disposition"]),
                tier=_escape(record["classification"]["delivery_tier"]),
                delivery=_escape(record["implementation"]["delivery_state"]),
            )
        )
    lines.extend([
        "",
        "## Source-closure exceptions",
        "",
        "| Stable ID | Classification | Source entries | Lifecycle | Review state | Reason |",
        "| --- | --- | --- | --- | --- | --- |",
    ])
    for record in exceptions:
        entries = ", ".join(f"`{_escape(value)}`" for value in record["source_entries"]) or "None observed"
        lines.append(
            "| `{id}` | `{classification}` | {entries} | `{lifecycle}` | `{review}` | {reason} |".format(
                id=_escape(record["id"]),
                classification=_escape(record["classification"]),
                entries=entries,
                lifecycle=_escape(record["lifecycle_status"]),
                review=_escape(record["review_state"]),
                reason=_escape(record["reason"]),
            )
        )
    lines.extend([
        "",
        "## Query summary",
        "",
        "| Query | Result |",
        "| --- | --- |",
        f"| Source coverage | {len(families)} normalized / {len(families)} locked families |",
        f"| Upstream lifecycle | {', '.join(f'`{key}` {value}' for key, value in sorted(lifecycle_counts.items()))} |",
        f"| Exception classes | {', '.join(f'`{key}` {value}' for key, value in sorted(exception_counts.items()))} |",
        f"| Product dispositions | {', '.join(f'`{key}` {value}' for key, value in sorted(disposition_counts.items()))} |",
        f"| Delivery states | {', '.join(f'`{key}` {value}' for key, value in sorted(delivery_counts.items()))} |",
        f"| Reviewed source identifiers | {sum(len(record['source']['source_identifiers']) for record in families)} |",
        f"| Distinct inclusion reasons | {len(set(record['inclusion_reason'] for record in families))} |",
        f"| Aliases / family relationships | {sum(len(record['aliases']) for record in families)} / {sum(len(record['relationships']) for record in families)} |",
        f"| Families with implementation evidence | {sum(bool(record['implementation']['implementation_evidence']) for record in families)} |",
        "",
        "## Nonclaims",
        "",
        "A row proves catalog identity and locked source coverage only. It does not prove that",
        "BlazeX will build, implement, support, render, port, package, or expose that family,",
        "and it establishes no .NET, Razor, NuGet, binary, source, or API compatibility.",
        "",
        "## Connections",
        "",
        "- [Catalog schema and governance](../../20-notes/blazex-component-catalog-schema-and-governance.md)",
        "- [Reference and inventory policy](../../20-notes/blazex-mudblazor-reference-and-inventory-policy.md)",
        "- [Source reconciliation report](mudblazor-v9-9-0-inventory-reconciliation.md)",
        "",
        "## Sources",
        "",
        "- [MudBlazor v9.9.0 reference lock](mudblazor-v9.9.0-reference-lock.json)",
        "- [MudBlazor v9.9.0 source-family snapshot](mudblazor-v9.9.0-source-families.txt)",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output differs instead of writing")
    arguments = parser.parse_args()
    try:
        catalog = json.loads(arguments.catalog.read_text(encoding="utf-8"))
        import validate_component_catalog as validator

        schema = validator.load_json(validator.CATALOG_SCHEMA_PATH)
        validator.validate_catalog_document(catalog, schema)
        rendered = render_catalog(catalog)
        if arguments.check:
            existing = arguments.output.read_text(encoding="utf-8")
            if existing != rendered:
                print(f"Generated component catalog is stale: {arguments.output}", file=sys.stderr)
                return 1
        else:
            arguments.output.write_text(rendered, encoding="utf-8", newline="\n")
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        print(f"Component catalog generation failed: {error}", file=sys.stderr)
        return 1
    action = "matches" if arguments.check else "wrote"
    print(f"Component catalog generation {action} {arguments.output}: {len(catalog['families'])} families, {len(catalog['exceptions'])} exceptions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
