#!/usr/bin/env python3
"""Generate the navigable BlazeX BH-00 baseline and BH-01 entry manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
ASSET_DIR = ROOT / "assets" / "bh-00-release"
CONTRACT_PATH = ASSET_DIR / "blazex-bh-00-governance-v0.1.0.json"
RELEASE_INDEX_PATH = ASSET_DIR / "blazex-bh-00-release-index-v0-1-0.md"
BH01_MANIFEST_PATH = ASSET_DIR / "blazex-bh-01-entry-manifest-v0-1-0.md"


def load_contract() -> dict[str, Any]:
    value = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("BH-00 governance contract must be an object")
    return value


def source_manifest_sha256(contract: dict[str, Any]) -> str:
    payload = json.dumps(contract["source_bindings"], sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()


def relative_link(source_path: str) -> str:
    absolute = (ROOT / source_path).resolve()
    return Path(os.path.relpath(absolute, ASSET_DIR)).as_posix()


def material_state(role: str) -> str:
    return {
        "repository-boundary": "authoritative-index",
        "vocabulary": "authoritative",
        "architecture-decision": "accepted-authoritative",
        "support-envelope": "proposed-candidate-unsupported",
        "catalog": "locked-authoritative",
        "classification": "accepted-contract-unimplemented",
        "quality": "proposed-unmeasured",
        "acceptance": "planned-unexecuted",
        "roadmap": "planned-program",
    }[role]


def render_release_index(contract: dict[str, Any]) -> str:
    release = contract["release"]
    entry = contract["bh01_entry"]
    lines = [
        "---",
        'title: "BlazeX BH-00 Product Contract Baseline v0.1.0"',
        "kind: map",
        'created: "2026-09-03"',
        "tags:",
        "  - archive-navigation",
        "  - bh-00",
        "  - product-contract",
        "  - release-index",
        "aliases:",
        '  - "BH-00 baseline v0.1.0"',
        "---",
        "",
        "# BlazeX BH-00 Product Contract Baseline v0.1.0",
        "",
        "> Generated by `generate_bh00_release.py` from the canonical governance contract. Edit governed sources, not this index.",
        "",
        "## Decision summary",
        "",
        f"- Release ID: `{release['release_id']}`",
        f"- Governance stage: `{contract['stage']}`",
        f"- Product-contract status: `{release['status']}`",
        f"- BH-01 entry decision: `{entry['decision']}`",
        f"- Bound source manifest SHA-256: `{release['source_manifest_sha256']}`",
        "- Browser/runtime/component support: unsupported and unproven",
        "- Runtime, benchmark, browser, accessibility, security, deployment, and release evidence: not executed",
        "- Accepted BH-00 exceptions: none",
        "",
        "BH-00 accepts a versioned product and evidence contract. It does not accept an implementation or browser release. BH-01 may proceed only after its detailed phase plan is separately approved and only as a stop/go feasibility baseline.",
        "",
        "## Authoritative contract set",
        "",
        "| ID | Role | State | Bound artifact | SHA-256 |",
        "| --- | --- | --- | --- | --- |",
    ]
    for source in contract["source_bindings"]:
        link = relative_link(source["path"])
        lines.append(
            f"| `{source['id']}` | `{source['role']}` | `{material_state(source['role'])}` | "
            f"[{Path(source['path']).name}]({link}) | `{source['sha256']}` |"
        )
    lines.extend([
        "",
        "## Governance and review artifacts",
        "",
        "- [Canonical governance contract](blazex-bh-00-governance-v0.1.0.json) — authored reconciliation, review, risk, release, and entry-decision source.",
        "- [Governance schema](blazex-bh-00-governance.schema.json) — machine structure and state constraints.",
        "- [Multidisciplinary review](blazex-bh-00-multidisciplinary-review-v0-1-0.md) — eight evidence-first discipline passes, findings, and risk disposition.",
        "- [Final BH-00 acceptance](blazex-bh-00-final-acceptance-v0-1-0.md) — integration result, milestone decision, evidence boundary, and delivery record.",
        "- [BH-01 entry manifest](blazex-bh-01-entry-manifest-v0-1-0.md) — generated bounded feasibility inputs and proof obligations.",
        "- [Phase 6 implementation evidence](../../60-planning/01-browser-host/bh-00-product-boundary-catalog-and-acceptance-contract/phase-06-implementation-evidence.md) — section delivery and reproducible verification record.",
        "",
        "## Material-state legend",
        "",
        "- **Authoritative/accepted:** governs current product and architecture semantics.",
        "- **Locked:** source/reference inventory is fixed at the named revision.",
        "- **Proposed/candidate/unsupported:** defines a future qualification boundary and is not support evidence.",
        "- **Unimplemented/unmeasured/unexecuted:** contract exists while product evidence does not.",
        "- **Deferred:** assigned to a named later milestone and not included in BH-00 delivery.",
        "- **Historical/superseded:** must remain linked when a future baseline replaces a record; none are introduced by v0.1.0.",
        "",
        "## Reconciliation and review closure",
        "",
        f"- Reconciliation checks: {len(contract['reconciliation_checks'])}/17 passed with zero authoritative conflict.",
        f"- Discipline reviews: {len(contract['reviews'])}/8 completed with no blocking outcome.",
        f"- Findings: {len(contract['findings'])} accepted follow-ups, zero blocking.",
        f"- BH-01 feasibility risks: {len(contract['risks'])} open with owners and stop conditions.",
        "- Source catalog/classification: 83 families and 12 exceptions, implementation unknown.",
        "- Quality/acceptance: 31 budgets, 21 gate requirements, 290 conditions, zero executed evidence.",
        "",
        "## Generation commands",
        "",
    ])
    lines.extend(f"- `{command}`" for command in release["generation_commands"])
    lines.extend(["", "## Validation commands", ""])
    lines.extend(f"- `{command}`" for command in release["validation_commands"])
    lines.extend([
        "",
        "## Change and supersession control",
        "",
        release["change_control"],
        "",
        release["supersession"],
        "",
        "## Explicitly deferred or unsupported",
        "",
        "- Exact working Popcorn/AtomVM/Phoenix/LiveView/LocalLiveView/browser toolchain: BH-01 proof, currently unproven.",
        "- Implemented semantic kernel and cross-backend portability: BH-02 and later.",
        "- Supported browser product and components: later milestone evidence, currently unsupported.",
        "- Production native-control, desktop/WebView, and standalone-Wasm hosts: outside browser 1.0 beyond the BH-02 portability spike.",
        "- .NET, Razor, Blazor binary, MudBlazor API, NuGet, or renderer compatibility: explicitly not a BlazeX goal.",
        "",
        "## Connections",
        "",
        "- [Governance and reconciliation policy](../../20-notes/blazex-bh-00-governance-reconciliation-policy.md)",
        "- [BH-00 plan](../../60-planning/01-browser-host/bh-00-product-boundary-catalog-and-acceptance-contract/README.md)",
        "- [Browser roadmap](../../20-notes/browser-host-implementation-milestones.md)",
        "",
    ])
    return "\n".join(lines)


def render_bh01_manifest(contract: dict[str, Any]) -> str:
    entry = contract["bh01_entry"]
    lines = [
        "---",
        'title: "BlazeX BH-01 Conditional Entry Manifest v0.1.0"',
        "kind: note",
        'created: "2026-09-03"',
        "maturity: developing",
        "tags:",
        "  - bh-01",
        "  - feasibility",
        "  - input-manifest",
        "  - stop-conditions",
        "aliases:",
        '  - "BH-01 entry manifest"',
        "---",
        "",
        "# BlazeX BH-01 Conditional Entry Manifest v0.1.0",
        "",
        "> Generated by `generate_bh00_release.py` from the canonical governance contract. This is not a BH-01 implementation plan or authorization to install dependencies.",
        "",
        "## Decision",
        "",
        f"- Decision: `{entry['decision']}`",
        f"- Decision ID: `{entry['decision_id']}`",
        f"- Scope: {entry['authorization_scope']}",
        "",
        entry["rationale"],
        "",
        "## Entry conditions",
        "",
    ]
    lines.extend(f"- {value}" for value in entry["conditions"])
    lines.extend(["", "## Input manifest", "", "| ID | Category | Owner | State | Required input |", "| --- | --- | --- | --- | --- |"])
    for item in entry["input_manifest"]:
        lines.append(f"| `{item['id']}` | `{item['category']}` | `{item['owner']}` | `{item['state']}` | {item['description']} |")
    lines.extend(["", "## Proof obligations", "", "| ID | Owner | Evidence | Stop? | Observable obligation |", "| --- | --- | --- | --- | --- |"])
    for proof in entry["proof_obligations"]:
        evidence = ", ".join(f"`{value}`" for value in proof["evidence_types"])
        lines.append(f"| `{proof['id']}` | `{proof['repository_owner']}` | {evidence} | {'yes' if proof['stop_on_failure'] else 'no'} | {proof['statement']} |")
    lines.extend(["", "## Stop conditions", ""])
    lines.extend(f"- {value}" for value in entry["stop_conditions"])
    lines.extend(["", "## Open feasibility risks", "", "| Risk | Likelihood | Impact | Owner | Stop condition |", "| --- | --- | --- | --- | --- |"])
    for risk in contract["risks"]:
        lines.append(f"| `{risk['id']}` | `{risk['likelihood']}` | `{risk['impact']}` | `{risk['owner']}` | {risk['stop_condition']} |")
    lines.extend(["", "## Prohibited actions", ""])
    lines.extend(f"- {value}" for value in entry["prohibited_actions"])
    lines.extend([
        "",
        "## Evidence boundary",
        "",
        "Every input is `required-unproven`. Conditional readiness means the questions, owners, traces, budgets, and stop rules are complete. It does not mean the candidate stack works or that BH-01 may begin without its own approved phase plan.",
        "",
        "## Connections",
        "",
        "- [BH-00 release index](blazex-bh-00-release-index-v0-1-0.md)",
        "- [Multidisciplinary review](blazex-bh-00-multidisciplinary-review-v0-1-0.md)",
        "- [BH-00 governance contract](blazex-bh-00-governance-v0.1.0.json)",
        "- [BH-00 Phase 6 plan](../../60-planning/01-browser-host/bh-00-product-boundary-catalog-and-acceptance-contract/phase-06-governance-review-and-bh-00-acceptance.md)",
        "",
    ])
    return "\n".join(lines)


def output_texts() -> tuple[str, str]:
    contract = load_contract()
    if contract["release"] is None or contract["bh01_entry"] is None:
        raise ValueError("governance contract has no release or BH-01 entry decision")
    return render_release_index(contract), render_bh01_manifest(contract)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--release-output", type=Path, default=RELEASE_INDEX_PATH)
    parser.add_argument("--entry-output", type=Path, default=BH01_MANIFEST_PATH)
    args = parser.parse_args()
    release_text, entry_text = output_texts()
    if args.check:
        stale = []
        for path, expected in ((args.release_output, release_text), (args.entry_output, entry_text)):
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path))
        if stale:
            print(f"BH-00 release generation is stale: {', '.join(stale)}", file=sys.stderr)
            return 1
        print("BH-00 release generation matches the committed baseline and BH-01 entry manifest.")
        return 0
    args.release_output.write_text(release_text, encoding="utf-8")
    args.entry_output.write_text(entry_text, encoding="utf-8")
    print("Generated BH-00 baseline index and BH-01 conditional entry manifest.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
